### ISSUE TITLE
Successful messages logged but no images are found in folder

### ISSUE THREAD

**Issue by btbjosh** [dariospadoni/aws-lambda-image-compressor#1]
My cloudwatch logs all say the processes were completed and the image was being uploaded to the bucket, but the bucket has nothing in it.

`2016-12-01T20:18:46.665Z uploading image EYuB7tLbLF8bFk9aJ/small/testfile.jpg to bucket testbucket-optim`

`2016-12-01T20:18:48.765Z	image uploaded`

Any idea where I might look to resolve this?

**Comment by dariospadoni** [comment]
If you haven't changed the code, the images are saved into a bucket having a name 
_< original bucket name >-optimized_
Is it in this bucket you are looking to? In case, please make sure it exists and check if you have the right permission

**Comment by btbjosh** [comment]
I did change the bucket to be a different bucket. I decided to check my policy on my role...

    {
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "logs:CreateLogGroup",
                "logs:CreateLogStream",
                "logs:PutLogEvents"
            ],
            "Resource": "arn:aws:logs:*:*:*"
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:GetObject",
                "s3:PutObject"
            ],
            "Resource": [
                "arn:aws:s3:::test/*"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:GetObject",
                "s3:PutObject"
            ],
            "Resource": [
                "arn:aws:s3:::test-optim/*"
            ]
        }
    ]
}

i think it might be a permission issue, but I can't tell.  Does this policy look usable?

**Comment by dariospadoni** [comment]
I have 2 policy on my role: one is the default AWSLambdaExecute, the second one is a custom inline policy which looks like this:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "Stmt1479486661000",
            "Effect": "Allow",
            "Action": [
                "s3:PutObjectAcl"
            ],
            "Resource": [
                "arn:aws:s3:::*"
            ]
        }
    ]
}
```

I don't see PutObjectAcl Action on your policy, this can be the reason.

**Comment by btbjosh** [comment]
oh ok! I'll try adding that action and see. Thanks!

**Comment by btbjosh** [comment]
Yep! That did the trick. Thanks.
