### ISSUE TITLE
Stream yields empty buffer error

### ISSUE THREAD

**Issue by Weijtmans** [dariospadoni/aws-lambda-image-compressor#2]
Hi,

First of all thanks for your script. It is extremely useful.
Unfortunately O get the following error: error during image optimization: Error: Stream yields empty buffer.

Do you have any idea where this comes from?

Kind regards

**Comment by dariospadoni** [comment]
I don't know exactly...perhaps it is a big image? Have you tried to use a longer timeout?

**Comment by Weijtmans** [comment]
Thanks for the reply. It seems to throw this error only with PNG images.

**Comment by dariospadoni** [comment]
I've just tested with a PNG image with transparency and it's working with my configuration...Can you share the error stack you have? What is your timeout and memory configuration?

**Comment by Weijtmans** [comment]
I solved it, somehow a dependency was corrupted. I also submitted a pull request to add the correct file-type to the uploaded images.

**Comment by dariospadoni** [comment]
Nice, happy you managed to solve. And thanks for your contribution.

**Comment by adityachowta** [comment]
Hi Weijtmans, im too facing the same issue. Can you describe how you solved the problem
